modules/localization/localization.scm
I added the option to provide alternative text in addition to the key to the localization table. The benefit is that if nonverbose keys are used, in case the localization entry cannot be found, still a meaningful string is displayed.
=> LOCALIZATION: add the option of adding default text in localization

modules/ln_glgui/pixmap.scm, plugins/waveoutput/waveoutput.scm
This change enables scaling images with a single factor.
It is useful for switching between different screen sizes.
In planning: defining one scaling measure and automated scaling of other based while maintaining aspect ratio (let me know if this is desirable)
=> MODULES:LN_GUI: adds scaling to pixmap

loaders/android/bootstrap.c.in, loaders/android/bootstrap.java.in, modules/audio/audiofile.scm, modules/scran/global-macros.scm, modules/scran/scran-macros.scm, modules/shadchen/LICENSE, modules/shadchen/README.md, modules/shadchen/global-macros.scm, modules/shadchen/tests.scm
This code includes (among a few other smaller changes), improved support for looping audio (android, ios and port_audio support) as well as my ml-style pattern-matching language (shadchen), as a module.
=> Add Shadchen pattern matcher to modules, improve looping sound support by enabling the ability to stop sounds

languages/scm.sh
This forces a rebuild of the ln_repl module to ensure that global macros are always up-to-date.  It's a bit heavy-handed, but it doesn't add much to the compile time, and is a much simpler fix than looking at the timestamp of every global-macros.scm file.
=> LN_REPL: (#122) Modify build process to always re-build ln_repl module

targets/linux/install
Changes from a hard-coded "Desktop" folder to the user's choice configured using XDG tool. Falls back to hard-coded choice if this is not available.
=> Respect the user's XDG Desktop folder on linux

targets/android/host_linux
In other words: a68aa5f4219a8ee512a8a25ed9ebef3adf4c4888 for linux hosts.
I also had to remove the `--ndk-dir` argument since the script told me it is no longer supported. I am using ndk r13.
=> Support x86 and don't expect android ndk version 4.8 on linux

modules/orientation/orientation.scm
Current implementation doesn't provide a function to distinguish inverted orientations. Could add a separate check for each orientation but this allows the existing behaviour to be unchanged (ie landscape/portrait is considered to be either of two orientations).
=> ORIENTATION: add check for inverted orientation (seascape/upsidedown)

modules/alist/alist.scm
timestamp is not always needed
=> ALIST adds function to insert/replace list item without timestamp

modules/ln_core/log.scm
Overwriting should IMHO not cause any harm.  However doing so make it
much easier to use other libraries written for gambit as it and still
learn about exceptions.
=> Overwrite make-thread with make-safe-thread

modules/quirc/quirc.scm
So far I've been unable to get any useful results from quirc.  The
silent fail however is not nice when debugging.
=> At least produce a debug log entry when quirc failes to decode.

loaders/android/bootstrap.java.in, make.sh, modules/ln_core/packtool.scm
Since Marshmallow permissions are not automatically granted as
specified in the Manifest.
As a consequence LN apps die when accessing the SDCard, e.g. when
unpacking embedded files.
This patch adds a fragile hack to enable an ifdef-alike trick to
exclude code portions when targeting older APIs and uses it to request
the permission at startup.  Plus create the system-directory if it
does not already exists.
=> Handle compilation and permissions for ANDROIDAPI>22.

modules/clipboard/clipboard.scm
On linux and win32 the code does so far not know whether or not the
clipboard has any content.
That's NOT changed by this patch.
However it's IMHO better to provide a false positive claiming
content (thus suggesting to the user to paste is even though that
would fail) than falsely claim nothing available thus preventing avail
content to be pasted.
=> Err on usability wrt. clipboard content.

modules/ln_store/data.scm, modules/rupi/rupicore.scm
grep does not show any more make-mutex (except for the one in `ide-repl-pump`) to be named.
=> Name mutex with the symbol they are bound to.

languages/scm.sh
This change allows to use things like
(cond-expand
(android ...code applicable on android targets only...)
(linux ...code applicable on linux targets only...)
(else ...code applicable on all other targets...))
NB:
1. According to SRFI-0 `cond-expand` is only mandatory on top level.
2. Most Scheme implementations (i.e., all I know of), including gambit
allow the use of `cond-expand` everywhere.
3. With this change all uses of `app:android?` at runtime could
eventually be replaced by compile time code expansion.
=> Enable use of cond-expand depending on SYS_PLATFORM.

loaders/android/bootstrap.java.in
On Android after API 22 there is the need to check permissions at runtime.
This would be a first shot on a simple interface.
=> Support to unify permission handling.

modules/ln_core/log.scm
Rationale
=========
1. While debugging it may be useful to switch logging on without having
to re-start the application.
2. Long running applications may want to switch to a new logfile.
Descriptions
============
New procedure `log-reset!` exported.  May be called to re-initialize
logging.
If the logdir has been removed, logging is disabled.  If it was
created anew, logging is started.
In any case, logging is switched to either:
- a new file using the naming convention as before; starting at the
`(current-time)`
- or into the file given as optional parameter to `log-reset!`
=> LOG: allow re-initializing logging at runtime

modules/ln_glcore/glcore-ffi.scm, modules/ln_glcore/glcore.scm
[Issue #234](https://github.com/part-cw/lambdanative/issues/234). 
The issue is that `_glCoreTextureCreate` sometimes does not properly set up the texture, but marks it as initialized anyway. This fix adds a further check on the proper operation of the GL Context, creates an error, and lets the texture be re-initialized on next call. I believe this stems from being called in a different thread from the main GL Context. 
This also fixes what I believe to be a typo in `_glCoreTextureBind`, and adds helpful functions `glGetError` and `glIsEnabled` to glcore-ffi.scm
=> Fix of Issue #234

modules/ln_core/list.scm
Changes implementation to not error out with a segmentation fault if
the list fed into list-head is shorter than the maximum length
requested by the call.
=> LNCORE: avoid SEGV in list-head

modules/ttf/ttf.scm
As far as I can tell there is no need to keep the raw reference to
compiled the u8vector of a texture/font once it's been processed.
Doing so the way it was done will install a global variable holding on
the garbage thus increasing the memory consumption for no good reason.
=> TTF: do not keep global reference to potential garbage

languages/scm.sh
Gambit allows to refer to various installation dependent directories
using the ~~NAME symtax - e.g., as in `(include "~~lib/my/file.scm")`.
However gambit is not aware of cross-compiling.  So `~~lib` will refer
to the hosts version.
This change adds another option to the gambit invocation, which allows
to distinguish between the host and the target specific files of
gambit.  At least for the library.
The use case this is required for is not (yet) publically available.
It involves a library wich includes gambit source code using
cond-expand to include use cases like file locking for instance -
which is a horror to provide in a platform agnostic way.
=> SCM: add target specific directory definition to gambit invocation

modules/ln_core/misc.scm
marked the old version as deprecated - better check for the symbol than the string
=> CORE: better version for function-defined?

modules/config/config.scm
While looking into patching gambc to support `when` and `unless` I discovered a better way to detect the gambit version.
=> CONFIG: replace version detection with native gambit feature

modules/redcap/redcap.scm
get fields such as get fields such as project_id, project_title, creation_time, production_time, in_production, project_language, purpose, purpose_other, project_notes, custom_record_label, secondary_unique_field, is_longitudinal, has_repeating_instruments_or_events, surveys_enabled, scheduling_enabled, record_autonumbering_enabled, randomization_enabled, ddp_enabled, project_irb_number, project_grant_number, project_pi_firstname, project_pi_lastname, display_today_now_button, missing_data_codes, external_modules
;; requires to run redcap v >10.0 on host to function properly
=> [REDCAP] adds redcap-project-info and optimises the redcap-import-file

loaders/common/main.c, modules/ln_glgui/glgui.scm, modules/ln_glgui/ln_glgui.scm
Note: When other threads notice that the GUI thread should stop
waiting and thus reducing responsiveness : call `(glgui-wakeup!)` .
=> GLGUI: reduce idle load

languages/scm.sh, modules/ln_core/ln_core.scm
The gambit optimizations `(block)` and `(not safe)` are annoying in
debug mode.
Without `(block)` we gain the ability to instrument global definitions.
Without `(not safe)` we gain Scheme-level errors for segmentation faults.
In case we need something in between, we better introduce additional option (or sub-options) like `stage` - which would apply all optimizations but still include instrumentation - and/or more to remove instrumentation but keep out optimizations.
Maybe just --- hm, have a way to override these things per module ;-).  THAT would enable us to inject variants via `SETUP` or other tricks.
=> SCM: in debug mode: enable more debugging

modules/eventloop/eventloop.scm
Disables mediscanner on android when terminating.
Provides temporary fix for #295 for those that need it, at least for API <25 (only ones tested)
=> EVENTLOOP adds backward compatible option to disable mediascanner 

modules/eventloop/eventloop.scm
Without `(block)` this module fails to link properly.
=> EVENTLOOP: add required declarations

languages/scm.sh, targets/linux/build-binary
enable C profiling on Linux.
So far, the `-pg` switch to actually enable profiling was not present in the final link step.
=> enable C profiling on Linux

modules/ln_glgui/primitives.scm
Note: In order to keep the patch resonable sized, this patch is only a
first of a serious of changes.
So far it only proofs the concept and cracks down on the most
prominent cases profiling the app revealed.
Over time the use of `assoc` on fonts should be phased out and
replaced with properly abstracted operations to enable the underlying
implementation to be changed.
=> GLGUI: reduce complexity of font operations.

modules/ln_core/time.scm
As I've seen this quasi-mistake often, I fell compelled to explain.
The code this is really, really code calling for two steps of rewite
for otimization:
(define (string->seconds str fmt . tz0)
(apply string->seconds~ (append (list str (ln:tildify fmt)) tz0)))
apply usually (and with gambit) takes possibly more arguments.  So
(apply f e1 e2 ... lst)
is the same as
(apply f (append (list e1 e2 ...) lst))
Therefore we better write:
(define (string->seconds str fmt . tz0)
(apply string->seconds~ str (ln:tildify fmt) tz0))
`apply` is usually less effective as a direct call.  For frequently
called code this counts.
Therefore we write better dispatch on tz0:
(define (string->seconds str fmt . tz0)
(if (pair? tz0)
(string->seconds~ str (ln:tildify fmt) (car tz0))
(string->seconds~ str …
=> CORE: optimize time formatting, fix typo and wrong comment

languages/scm.sh
This is the smallest change and most generic way I could come up with to tell the Scheme compiler more about the target environment.
Note that the `export`ed list might need to grow or being cut down.  Right now it's just a suggestion.  It will also require some care, as it is now "more-or-less-documented" once those build parameters where exported.
`SYS_ANDROIDAPI` looks right now like the minimum to make with #256 available on both older and newer versions.
=> BUILD: export well known build parameters to gambit compiler

modules/ln_core/utf8string.scm
Until now errors in UTF-8 encoded strings are raised as an error in `string-ref '( ` *unsigned-int8* ` 1)` - which is not too helpful to locate the root cause.
With this change those errors are by default still errors, however with the string and offset of the offending byte in the error.
New is an optional second parameter `encoding-error` to **`utf8string->unicode`** - by default `#t` - which may be `#f` for *silent replacement*, `#t` for the default, which is calling the also new procedure `utf8string->unicode:on-encoding-error` with no arguments to obtain a handler to be called with two arguments, the string and offending offset and insert the value returned from the handler (if any) or a procedure to be used as if it was returned from calling `utf8string->unicode:on-encoding-error` …
=> CORE: flexible UTF-8 encoding error handling

make.sh
This changes the way `add_items_int` handles loops in item dependencies (MODULES and PLUGINS).
Background:
Items are added recursively. Items are added to the list "items", and parent items are added to a stack, "lasti". Items that are already in the item list are skipped, since they have already been added.
Change:
Similarly, we can check if the current item is already in the "lasti" stack, and skip those as well. This allows for graceful handling of dependency loops (a parent item is encountered that is already in the parent stack).
=> MAKE.SH: handle module/plugin dependency loops

modules/download/download.scm
the two highest char of file size were not extracted. 
now force float division
=> DOWNLOAD fixes the extraction of download file size and status calculation

targets/android/build-binary
Generalizes the concept working for the app itself to the modules it includes: a subdirectory `android_jars` content it shipped in `libs`.
Edit: should help wit #338 and friends.
=> ANDROID: include JAR files from modules

languages/scm.c, loaders/hook/hook.c, modules/config/config.scm, modules/ln_core/log.scm
With libgambit this errors out for me for unbound variables like this:
Code: `(unbound display)` Error:
Thread "primordial": (#!unbound '#<procedure #15 display>): Operator is not a PROCEDURE
Unfortunately ___cleanup(); in libgambit will still raise a deadlock
exception in log-trace.
=> CORE: try to avoid calling into Scheme after exit.

modules/ln_core/log.scm
This has been tested with Gambit 4.9.3 only.
As the procedures being used are documented in Gambc 4.7.9 too, it
SHOULD work there as well.
=> CORE: log exceptions with context

apps/DemoCamera/ANDROID_xml_services, apps/DemoCamera/xml/file_paths.xml, loaders/android/bootstrap.java.in, modules/camera/ANDROID_java_activityadditions, modules/camera/ANDROID_java_imports, modules/videoplayer/ANDROID_java_activityadditions, modules/videoplayer/ANDROID_java_imports, targets/android/build-binary
Updates build-binary to locate the support.v4 library for FileProvider. Uses FileProvider to properly obtain URIs and pass permissions for URI access. Addition of onRequestPermissionsResult to bootstrap.java.in to fix permission requests hanging. Apps that use FileProvider to pass URIs to activities must include ANDROID_xml_services and xml/file_paths.xml
=> CAMERA(Android): use FileProvider to read and write data

modules/clipboard/ANDROID_c_additions
warning: returning 'const char *' from a function with result type 'char *' discards qualifiers
=> CLIPBOARD: fix compiler complaints

loaders/android/bootstrap.c.in
Fixes the issue in
https://github.com/part-cw/lambdanative/commit/7561c9a28036d5d7b92c4078fdd3ea1f924992d7#commitcomment-44425578
=> ANDROID: do not call ReleaseStringUTFChars with an unrelated pointer

loaders/android/bootstrap.java.in
The patch fixes the main issue created in the hotfix wrt. `requestAllPersissions` and friends when I discovered that `onCreate` may be called several times per lifetime of an app.
PS: sorry for the removal of offending white space.  I'm busy.  Just delete those random blanks as a drive-by-patch, please.  They do IMHO more harm than good.
=> ANDROID: Fix setContentView wrt. static declaration by 20b33a1

modules/generalized-arrays/generalized-arrays.scm, modules/generalized-arrays/test-arrays.scm
These changes have been tested in both Gambit-C 4.7.9 and Gambit 4.9.2.
These changes are in response to comments by Joerg Wittenberger.
Here we try to speed up the implementation by a number of techniques:
1.  Cache often-accessed properties of intervals (dimension and volume) and arrays (array-elements-in-order?).
2.  Employ fixnum operations by assumeing that the lengths of vectors and the maximum number of arguments to functions are fixnums.  Add an option to the test suite to generate random intervals with bignum limits to test that we didn't use fixnum arithmetic where generic arithmetic is needed.  (This caught a bug in array-tile.)
3.  Newly allocated specialized arrays always store their elements adjacently and in order, so store that knowledge in the array.  If an array has its …
=> Improve speed of generalized-arrays module.

modules/redcap/redcap.scm
`(redcap:list->xmlstr ... )` crashed when in the list a non-string was (like '#f') 
This adds an extra check and replaces non-strings with "NA" to prevent unecessary crashes
=> REDCAP: fix parsing of xml from list. make check that value is string

modules/download/download.scm
When header was 'false' the logic comparisons failed. 
Also: when file can't be downloaded drop a warning instead of a status log
=> [FIX][DOWNLOAD] fixes logic for checking header 

libraries/libfreetype/make.sh
Roll back libfreetype version to 2.10.1 to prevent:
#428
=> Change libraries/libfreetype/make.sh

libraries/libdmtx/make.sh, libraries/libfcgi/make.sh, libraries/libfreetype/make.sh, libraries/libgd/make.sh, libraries/libopus/make.sh, libraries/libportaudio/make.sh, libraries/libuuid/make.sh, libraries/libzip/make.sh, modules/httpsclient/httpsclient.scm
enables cross compilation on WSL2 for win32. addresses issue #430 
tested on all Demo* apps and a few private ones.
Currently fails on LNHealth because of libuuid with 
```
randutils.c:17:10: fatal error: sys/syscall.h: No such file or directory
17 | #include <sys/syscall.h>
|          ^~~~~~~~~~~~~~~
```
=> [FIX] [WSL2] cross-compilation on WSL2 for windows requires special build config

configure
Little patch to support m1/m2 (apple silicon) Macs.
I testest with DemoSchemeAndC (needs brew install autoconf) and Calculator (need brew install imagemagick)
=> M1/M2 (apple silicon) macosx support

libraries/libminizip/ioapi_mem.c, libraries/libminizip/minizip.c
On Windows platforms, long is always 4 bytes, which causes truncation of 64-bit pointers.
=> Compatible with Windows platform long size
