part-cw/lambdanative

- modules/ln_glgui/horizontalvaluepicker.scm
- modules/ln_glgui/ln_glgui.scm
Added:
modules/ln_glgui/horizontalvaluepicker.scm
Modified:
modules/ln_glgui/ln_glgui.scm
-added horizontalvaluepicker
> MODULES:LN_GLGUI: Added horizontalvaluepicker

- loaders/android/bootstrap.java.in
- modules/audio/audiofile-parser.scm
- modules/audio/audiofile.scm
Hi Lambdanative folks,
This pull request contains code to add audiomixing support for Android, port audio and IOS devices. The port audio and android versions are tested and working, but the iOS changes, while simple, have not been tested on my device - I hope to get a developer's Macbook sometime next month and then we can resolve this issue.
I _believe_ that windows already supported audio mixing but have no idea about Blackberry. 
I've tried to separate the iOS specific code in separate commits, so it should be easy to revert those in particular if I have made a mess. Let me know if I can help with any other issues - I am busy, but I really like the project and want to keep it active!
> Audio mixing support for various platforms

- modules/alist/alist.scm
Simple code has been added to the association list library to persist and load alists to and from files. Useful for saving small amounts of state between runs.
> Added code to save and load association lists.

- modules/ln_repl/ln_repl.scm
Upgraded ln_repl module as per issue #117. Tested on linux and android.
> Ln repl enhancements

- modules/scran/scran.scm
These three commits contain two superficial bug fixes and feature improvements, isolated to the module scran, and one important bug fix relating to resetting a set of scran systems.
> Scran bug fixes.

- modules/scran/scran.scm
This commit adds three unit tests to scran, plus a few more utilities.
> Scran unit tests + utils.

- loaders/ios/novocaine.m
- loaders/macosx/novocaine.m
> Call [super dealloc]

- modules/uiform/uiform.scm
bug fixes for better form performance
> Patch uiform slider

- scripts/lambdanative
By allow she/he pass it to the script, he/she is not required to make
any changes to the lambdanative script.
> Allow user to pass LAMBDANATIVE variable to script

- languages/scm.c
- libraries/libgambit/make.sh
- modules/config/config.scm
Change USE_EXPERIMENTAL in languages/scm.c to switch between gambc
4.7.9 and gambit 4.9.2.
> Update to recent gambit.

- languages/scm.sh
This patch provides a partial way to specify compile time macros.
Iff there is a file with the same basename and an extension .sch
the latter is loaded into gambit via -e option.
Caveat:
lambdanative does not check the .sch file for modifications like it
does with the .scm files.  Updates to the file do not trigger a
recompile.
A real solution would be to support r7rs style library declarations.
> Support macro loading per file.

- modules/uiform/uiform.scm
function to clear required flags in store (i.e. when a reset is needed after a cancel)
> UIFORM: adds function to clear required field

- modules/magnetometer/ANDROID_c_additions
- modules/magnetometer/ANDROID_java_activityadditions
- modules/magnetometer/ANDROID_java_oncreate
- modules/magnetometer/ANDROID_java_onresume
- modules/magnetometer/ANDROID_java_onsensorchanged
- modules/magnetometer/ANDROID_java_variables
- modules/magnetometer/ANDROID_xml_permissions
- modules/magnetometer/magnetometer.scm
Adds compass sensor readings (only Android available, if someone with iOS testing possibilities cann add those too?)
demo app for all sensors will follow...
> [NEW][MAGNETOMETER] add compas reading to modules for android

- modules/rotation/ANDROID_c_additions
- modules/rotation/ANDROID_java_activityadditions
- modules/rotation/ANDROID_java_oncreate
- modules/rotation/ANDROID_java_onresume
- modules/rotation/ANDROID_java_onsensorchanged
- modules/rotation/ANDROID_java_variables
- modules/rotation/ANDROID_xml_permissions
- modules/rotation/rotation.scm
this module adds IMU process rotation data as sensor module. Only works for Android atm. 
Would be great if someone can expand with iOS version
> [NEW][ROTATION] add the android module for determining phone rotation

- modules/ln_glgui/chat.scm
Additionally I had to re-format the source according to widespread
conventions for readbility and used keyword like `when` and `unless`
to make the source more compact and easier to digest.
Sorry for the latter.
> GLGUI: chat - added comments and minor runtime optimizations

- modules/download/download.scm
analog to redcap in commit #331
> [download] adds a threadsleep for mobile devices to keep GUI responsive

- libraries/libpcap/make.sh
This modification likely requires review!  I just tried to use it,
found not working and changed what was required in my case.
No knowledge here what could break.
> LIBPCAP: change build

- modules/ln_glgui/primitives.scm
Note: length is O(n) - pull it out of loops where possible especially
in often invoked code like "primitives".
NB: Same warning applies to list-ref .
This patch only goes for the low hanging fruit where things should be obvious.
> GLGUI: fix potentialy exponential complexity - avoid use of length

- modules/ln_glgui/chat.scm
Until now the chat widget caches a pre-processed version of the
list of entries to display keyed on the `length` of the list.
Avoiding some exponential complexity during drawing, there was and
upper bound of the length maintained.  This broke once the list grew
beyond that.
This change slightly modifies the cache - and therefore renames it
within the widget.
The new caching tests ONLY whether or not the old list is the SAME in
terms of `eq?` as the new one.  It INTENSIONALY does NOT try to detect
updates to the components of the list.  This decision was made because
drawing happens much, much more frequent than updates.  It is trivial
on the update side to avoid side effects, but costly on the drawing
side to detect them.
> GLGUI: fix chat widget update.

- modules/download/download.scm
- adds option to download files to a temporary local file instead of memory. This is especially useful for larger files which will slow down the system otherwise
- adds option to read download progress based on temp file size
> DOWNLOAD adds option to download files to a temporary local file

- languages/scm.sh
This might be helpful to track the breakage under mac down.
Also likely helpful to reveal bottlenecks by profiling.
> enable C profiling and debugging of Scheme code.

- modules/download/download.scm
this feature was previously removed as it slowed down slow connections even more. 
Does check for download size and sleeps under android and iOS approx only every 1MB
> DOWNLOAD reintroduces the sleep in android and ios mode, checks for minimal download size

- languages/scm.sh
This enables compile-time instrumentation/alteration of code depending
on the configured options.
> define cond expand feature debug

- loaders/android/bootstrap.c.in
there will be more in audio at least, not yet written.
> ANDROID: JNI error checking and free local references

- modules/uiform/uiform.scm
replaces a static color fade with the selcolor for nicer GUI
> [MOD][UIFORM] adds the option to set color for selected  checklist

- README.md
https://github.com/part-cw/lambdanative/issues/448
> uSquish no longer in app stores

- libraries/libgd/make.sh
Closes https://github.com/part-cw/lambdanative/issues/451
> Obtain libgd from main repository
